### ISSUE TITLE
How did you deal with nil mention? 

### ISSUE THREAD

**Issue by wanicca** [shyamupa/xling-el#2]
If there are no candidates, it's easy to tag the mention with nil. However sometimes a mention has generated candidates, but all of them are wrong. How did you deal with this case?

**Comment by shyamupa** [comment]
This is not dealt with currently in the system. In this case, the model will still predict an entity as the disambiguation. One way to handle this is to train a classifier (like [1]) for deciding if the disambiguation is correct. 
[1] [Local and Global Algorithms for Disambiguation to Wikipedia](https://dl.acm.org/citation.cfm?id=2002642)

**Comment by wanicca** [comment]
Ok, thanks!

> This is not dealt with currently in the system. In this case, the model will still predict an entity as the disambiguation. One way to handle this is to train a classifier (like [1]) for deciding if the disambiguation is correct.
> [1] [Local and Global Algorithms for Disambiguation to Wikipedia](https://dl.acm.org/citation.cfm?id=2002642)
